baseURL = "https://jerodsanto.net"
languageCode = "en-us"
title = "Jerod Santo"
disableKinds = ["taxonomy", "term", "section"]

[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"

[params]
  author = "Jerod Santo"
  description = "Buy the truth, and do net sell"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false

[permalinks]
  posts = "/:year/:month/:title/"

[pagination]
  pagerSize = 10
