baseURL = "https://jerodsanto.net"
languageCode = "en-us"
title = "Jerod Santo"
disableKinds = ["taxonomy", "term", "section"]

[outputs]
  home = ["HTML", "RSS", "POSSE"]

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"

[outputFormats.POSSE]
  mediatype = "application/rss+xml"
  baseName = "posse"

[params]
  author = "Jerod Santo"
  description = "Buy the truth, sell it not"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[permalinks]
  posts = "/:year/:month/:slug/"

[pagination]
  pagerSize = 10
